module.exports = {
  HTTP_OK_STATUS: 200,
  HTTP_CREATED_STATUS: 201,
  HTTP_NO_CONTENT_STATUS: 204,
  HTTP_BAD_REQUEST_STATUS: 400,
  HTTP_UNAUTHORIZED_STATUS: 401,
  HTTP_NOT_FOUND_STATUS: 404,
  HTTP_CONFLICT_STATUS: 409,
  HTTP_UNPROCESSABLE_ENTITY_STATUS: 422,
};